apiVersion: k8s.chainer.org/v1alpha1
kind: ChainerJob
metadata:
  name: example-chainerjob
spec:
  # name of secret
  sshKey: example-ssh-key
  master:
    # you can write PodTemplate freely
    # several configs will be injected by chainer-operators
    template:
      spec:
        # securityContext:
        #   runAsUser: 1000
        #   fsGroup: 1000
        volumes:
        - name: chainermn-repo
          emptyDir: {}
        containers:
          # this container set up sshd server for mpi jobs
        - name: chainer
          image: everpeace/kube-openmpi:0.6.0-cuda8.0-nccl2.1.4-1-chainer4.0.0b4-chainermn1.2.0
          volumeMounts:
          - name: chainermn-repo
            mountPath: /chainermn-examples
            subPath: chainermn/examples
          # command: will be overridden by chainer-operator
          args:
            - |
              mpiexec --allow-run-as-root\
                --hostfile /chainerjob/generated/hostfile \
                --display-map -n 2 -npernode 1 \
                --mca orte_base_help_aggregate 0 \
                python3 /chainermn-examples/mnist/train_mnist.py -b 10 -e 2
        initContainers:
        - name: chainermn-fetch
          image: gcr.io/google_containers/git-sync:v2.0.6
          volumeMounts:
          - name: chainermn-repo
            mountPath: /git
          env:
          - name: GIT_SYNC_REPO
            value: https://github.com/chainer/chainermn.git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_DEST
            value: chainermn
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_WAIT
            value: "120"
  worker:
    replicas: 2
    # you can write PodTemplate freely
    # several configs will be injected by chainer-operators
    template:
      spec:
        # securityContext:
        #   runAsUser: 1000
        #   fsGroup: 1000
        volumes:
        - name: chainermn-repo
          emptyDir: {}
        containers:
          # this container set up sshd server for mpi jobs
        - name: chainer
          image: everpeace/kube-openmpi:0.6.0-cuda8.0-nccl2.1.4-1-chainer4.0.0b4-chainermn1.2.0
          volumeMounts:
          - name: chainermn-repo
            mountPath: /chainermn-examples
            subPath: chainermn/examples
        # command: will be overridden by chainer-operator
        initContainers:
        - name: chainermn-fetch
          image: gcr.io/google_containers/git-sync:v2.0.6
          volumeMounts:
          - name: chainermn-repo
            mountPath: /git
          env:
          - name: GIT_SYNC_REPO
            value: https://github.com/chainer/chainermn.git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_DEST
            value: chainermn
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_WAIT
            value: "120"
