apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chainerjobs.k8s.chainer.org
spec:
  group: k8s.chainer.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: chainerjobs
    singular: chainerjob
    kind: ChainerJob
    shortNames: ["chj"]
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            sshKey:
              type: string
            master:
              type: object
              properties:
                # pod template object
                template:
                  type: object
            worker:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 0

---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: chainerjob-operator-v1alpha1
spec:
  generateSelector: true
  parentResource:
    apiVersion: k8s.chainer.org/v1alpha1
    resource: chainerjobs
  childResources:
  - apiVersion: v1
    resource: services
  - apiVersion: v1
    resource: configmaps
  - apiVersion: v1
    resource: pods
  - apiVersion: apps/v1
    resource: statefulsets
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://chainerjob-operator-v1alpha1.metacontroller/sync-cluster
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chainerjob-operator-v1alpha1
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainerjob-operator
      version: v1alpha1
  template:
    metadata:
      labels:
        app: chainerjob-operator
        version: v1alpha1
    spec:
      containers:
      - name: controller
        image: metacontroller/jsonnetd:0.1
        workingDir: /chainerjob/operator/hooks
        volumeMounts:
        - name: hooks
          mountPath: /chainerjob/operator/hooks
      volumes:
      - name: hooks
        configMap:
          name: chainerjob-operator-v1alpha1-hooks

---
apiVersion: v1
kind: Service
metadata:
  name: chainerjob-operator-v1alpha1
  namespace: metacontroller
spec:
  selector:
    app: chainerjob-operator
    version: v1alpha1
  ports:
  - port: 80
    targetPort: 8080
