apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chainerjobs.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: chainerjobs
    singular: chainerjob
    kind: ChainerJob
    shortNames: ["chjobs"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: chainer-operator-v1alpha1
spec:
  generateSelector: true
  parentResource:
    apiVersion: kubeflow.org/v1alpha1
    resource: chainerjobs
  childResources:
  - apiVersion: v1
    resource: serviceaccounts
  - apiVersion: rbac.authorization.k8s.io/v1
    resource: roles
  - apiVersion: rbac.authorization.k8s.io/v1
    resource: rolebindings
  - apiVersion: v1
    resource: configmaps
  - apiVersion: v1
    resource: services
  - apiVersion: batch/v1
    resource: jobs
  - apiVersion: apps/v1
    resource: statefulsets
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://chainer-operator-v1alpha1.metacontroller/sync-cluster
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chainer-operator-v1alpha1
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainer-operator
      version: v1alpha1
  template:
    metadata:
      labels:
        app: chainer-operator
        version: v1alpha1
    spec:
      containers:
      - name: controller
        image: everpeace/jsonnetd:0.1
        workingDir: /chainerjob/operator/hooks
        volumeMounts:
        - name: hooks
          mountPath: /chainerjob/operator/hooks
      volumes:
      - name: hooks
        configMap:
          name: chainer-operator-v1alpha1-hooks

---
apiVersion: v1
kind: Service
metadata:
  name: chainer-operator-v1alpha1
  namespace: metacontroller
spec:
  selector:
    app: chainer-operator
    version: v1alpha1
  ports:
  - port: 80
    targetPort: 8080
