apiVersion: kubeflow.org/v1alpha1
kind: ChainerJob
metadata:
  name: examplejob-chainermn
spec:
  backend: mpi
  master:
    template:
      spec:
        containers:
        - name: chainer
          image: everpeace/chainermn:1.3.0
          command:
          - sh
          - -c
          - |
            mpiexec -n 2 -N 1 --allow-run-as-root --display-map \
            python3 /train_mnist.py -e 2 -b 10
  worker:
    replicas: 2
    template:
      spec:
        containers:
        - name: chainer
          image: everpeace/chainermn:1.3.0
          command:
          - sh
          - -c
          - |
            while true; do sleep 1 & wait; done
