apiVersion: kubeflow.org/v1alpha1
kind: ChainerJob
metadata:
  name: examplejob-chainer
spec:
  backend: mpi
  master:
    template:
      spec:
        containers:
        - name: chainer
          image: everpeace/chainer:4.1.0
          command:
          - sh
          - -c
          - |
            python3 /train_mnist.py -e 2 -b 100
